name: Python Linting

on:
  push:
    branches: [main, postbuild]
  pull_request:
    branches: [main, postbuild]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install linting dependencies
        run: |
          pip install -r requirements-linting.txt

      - name: flake8
        run: flake8

      - name: Check sorted python imports using isort
        run: |
          isort . -c -i 4 -l 79
