name: Release nlp-feature-extractors to PyPI

# trigger manually only ("collaborator" or more permissions required)
on:
  workflow_dispatch:
    inputs:
      type:
        description: "Test or Prod PyPI?"
        required: true
        default: "Test"

jobs:
  release-nlp-feature-extractors:
    runs-on: ubuntu-latest
    steps:
      - name: fail if Test nor Prod
        if: ${{ ! (github.event.inputs.type == 'Test' || github.event.inputs.type == 'Prod') }}
        run: |
          echo "Only Test or Prod can be used."
          exit 1

      # build wheel
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: update and upgrade pip, setuptools, wheel, and twine
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine

      - name: install requirements.txt for nlp-feature-extractors
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
        working-directory: nlp_feature_extractors

      - name: pip freeze
        run: pip freeze

      - name: build wheel for nlp-feature-extractors
        run: python setup.py sdist bdist_wheel
        working-directory: nlp_feature_extractors

      - name: install nlp-feature-extractors wheel locally
        run: find ./dist/ -name '*.whl' -exec pip install {} \;
        working-directory: nlp_feature_extractors

      # publish to PyPI
      - name: Publish nlp-feature-extractors package to Test PyPI
        if: ${{ github.event.inputs.type == 'Test' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN_NLP_FEATURE_EXTRACTORS }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: nlp_feature_extractors/dist/
      - name: Publish nlp-feature-extractors package to PyPI
        if: ${{ github.event.inputs.type == 'Prod' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN_NLP_FEATURE_EXTRACTORS }}
          packages_dir: nlp_feature_extractors/dist/
